// table schema generated by introspection
import { timestamps } from '@app/common/columns.helpers';
import {
  mysqlTable,
  primaryKey,
  unique,
  int,
  varchar,
} from 'drizzle-orm/mysql-core';

export const userSchema = mysqlTable(
  'users',
  {
    id: int().autoincrement().primaryKey(),
    email: varchar({ length: 255 }).notNull(),
    password: varchar({ length: 255 }).notNull(),
    name: varchar({ length: 255 }).notNull(),
    authProvider: varchar('auth_provider', { length: 255 }).notNull(),
    profilePicture: varchar('profile_picture', { length: 255 }),
    ...timestamps,
  },
  (table) => [
    primaryKey({ columns: [table.id], name: 'users_id' }),
    unique('users_email_unique').on(table.email),
  ],
);
