// table schema generated by introspection
import { timestamps } from '@app/common';
import { USER_ROLES, UserRole } from '@app/common/types/enum/user.role.enum';
import {
  mysqlTable,
  int,
  varchar,
  mysqlEnum,
  datetime,
  index,
} from 'drizzle-orm/mysql-core';
import { AccountStatusEnum } from '@app/common/types';

export const userSchema = mysqlTable(
  'users',
  {
    id: int().autoincrement().primaryKey(),
    firstName: varchar('first_name', { length: 255 }).notNull(),
    middleName: varchar('middle_name', { length: 255 }),
    lastName: varchar('last_name', { length: 255 }).notNull(),
    email: varchar({ length: 255 }).notNull().unique(),
    password: varchar({ length: 255 }).notNull(),
    authProvider: varchar('auth_provider', { length: 255 }).notNull(),
    phoneNumber: varchar('phone_number', { length: 255 }),
    role: mysqlEnum('role', USER_ROLES)
      .notNull()
      .default(UserRole.ADMIN),
    address: varchar({ length: 255 }),
    status: mysqlEnum(
      'status',
      Object.values(AccountStatusEnum) as [string, ...string[]],
    ).notNull(),
    profilePicture: varchar('profile_picture', { length: 255 }),
    resetPasswordToken: varchar('reset_password_token', { length: 64 }),
    resetPasswordTokenExpiresAt: datetime('reset_password_token_expires_at'),
    lastLoginAt: datetime('last_login_at', { mode: 'string' }),
    ...timestamps,
  },
  (table) => ({
    nameIndex: index('name_index').on(table.email),
  }),
);
