// table schema generated by introspection
import { timestamps } from '@app/common/columns.helpers';
import {
  mysqlTable,
  primaryKey,
  unique,
  serial,
  varchar,
} from 'drizzle-orm/mysql-core';

export const usersTable = mysqlTable(
  'users',
  {
    id: serial().notNull(),
    email: varchar({ length: 255 }).notNull(),
    password: varchar({ length: 255 }).notNull(),
    name: varchar({ length: 255 }).notNull(),
    authProvider: varchar('auth_provider', { length: 255 }).notNull(),
    profilePicture: varchar('profile_picture', { length: 255 }),
    ...timestamps,
  },
  (table) => [
    primaryKey({ columns: [table.id], name: 'users_id' }),
    unique('id').on(table.id),
    unique('users_email_unique').on(table.email),
  ],
);
